### ISSUE TITLE
Does not accept friend requests after scheduled "reconnect"

### ISSUE THREAD

**Issue by itsTKRaz** [Vrekt/FortniteXMPP2#2]
Can there be made an option to auto-accept any and all friend requests.  Or at least, a loop that checks every 1 minute to accept any pending requests?  I do not see any methods to fetch pending friend requests.

**Comment by Vrekt** [comment]
Pending as in, the bot/current account sent the friend request? Or the other way around?

**Comment by Vrekt** [comment]
About the 1 minute thing, there are currently listeners to accept friend requests. Like so:
```java
                xmpp.friend().addFriendListener(new FriendListener() {
                @Override
                public void onFriendRequestReceived(String accountId) {
                    xmpp.friend().acceptOrSendFriendRequest(accountId);
                }
            });
```

**Comment by itsTKRaz** [comment]
That's just the problem.  The listener doesn't always accept the friend request.  The bot is never sending the friend request, it's definitely the other way around.  And there are times where even after multiple attempts of deleting the request and sending it again, as the user trying to friend the bot.

**Comment by itsTKRaz** [comment]
Additionally, I can manually log into the bot accounts, and I can see up to 25+ pending friend requests that the bot has not automatically accepted.  This happens typically after a connection reset.

**Comment by Vrekt** [comment]
Interesting okay, and just curious what version are you using?

**Comment by itsTKRaz** [comment]
This has been happening since 2.1.  I was on 2.6, but just updated it to 2.7.  These issues don't typically happen right away, but after a reconnect, so only time will tell if it happens again on latest.

**Comment by Vrekt** [comment]
Looking into it right now, will respond soon.

**Comment by Vrekt** [comment]
Also, as in a reconnect do you mean the connection closed with error so it automatically reconnects, or are you using keep alive, or are you manually closing and reconnecting?

**Comment by itsTKRaz** [comment]
I was using the keepAlive method to reconnect after 6 hours.

**Comment by itsTKRaz** [comment]
Or otherwise, a manual method.

**Comment by Vrekt** [comment]
When it fails to accept a friend request do you see a message similar to this in logs?
```
Apr 06, 2019 1:21:55 PM me.vrekt.fortnitexmpp.friend.DefaultFriendResource acceptOrSendFriendRequest
WARNING: Could not accept a friend request from: status code: <>
```
If not, this (maybe possible could) indicate it may be a problem with your code. I haven't encountered any behavior where it fails to accept, (although I'm still looking around/testing stuff)

**Comment by Vrekt** [comment]
Also, if you want to find all pending friend requests you can use the `fortnite-2` lib.
```
xmpp.fortnite().friend().findAllRequestsBySessionAccountId().ifPresent(list -> {});
```
This uses the HTTP endpoint.

**Comment by itsTKRaz** [comment]
The only error I get in my log would be this:

`Apr 06, 2019 5:48:16 AM org.jivesoftware.smack.AbstractXMPPConnection$3 run
WARNING: Sending listener threw exception
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
	at org.jivesoftware.smack.roster.Roster.setOfflinePresences(Roster.java:1213)
	at org.jivesoftware.smack.roster.Roster.access$600(Roster.java:94)
	at org.jivesoftware.smack.roster.Roster$4.processStanza(Roster.java:351)
	at org.jivesoftware.smack.AbstractXMPPConnection$3.run(AbstractXMPPConnection.java:952)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
`

This occurs directly after an XMPP reconnect (the keepalive)

I've actually been working for the past 4 days on rewriting a lot of code trying to optimize as much as possible on my bot.  I'll try that method though.

**Comment by Vrekt** [comment]
On reconnect you can:
```
xmpp.fortnite().friend().findAllRequestsBySessionAccountId().ifPresent(list -> {});
```
And then:
```
// for each account Id in list
xmpp.fortnite().friend().addOneByAccountId("accountId");
```

If you want to directly handle things yourself and catch the IOException. Sometimes exceptions may get silenced so it could be hard to tell what exactly is going on. Also the exception you posted could be related to trying to send something when its reconnecting. (atleast I think so), I would recommend stopping any code you have from running when the XMPP service is reconnecting.
```
            xmpp.onReconnect(v -> {
                // stop code
            });
            
            xmpp.onConnected(v -> {
                // resume normal operation
            });
```

**Comment by itsTKRaz** [comment]
I'll do that.  Thank you very much 👍

**Comment by badvixo** [comment]
Vrekt accept my request
