### ISSUE TITLE
How to change skin in game

### ISSUE THREAD

**Issue by ghost** [Vrekt/FortniteXMPP2#4]
How to change skin in game?

**Comment by Vrekt** [comment]
```
PartyMemberData.forNewSkin(skinName);
```

**Comment by ghost** [comment]
if (message.getMessage().equalsIgnoreCase("test")) {
		    	PartyMemberData.forNewSkin("AthenaCharacter:CID_386_Athena_Commando_M_StreetOpsStealth");
		    }
this not working

**Comment by ghost** [comment]
Without AthenaCharacter:, too not working.

**Comment by Vrekt** [comment]
```
final var data = PartyMemberData.forNewSkin(Skin.CID_001_Athena_Commando_F_Default.name());
data.setPartyIdAndBuild(party.partyId());
        
resource.sendRequestTo(data, whoeverItsGoingTo);
```

**Comment by Vrekt** [comment]
Skin names should just be "CID_XXX_etc"
